### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Hilljack4n6** [iandday/o365AuditParser#1] opened 2023-04-21 13:53 UTC
Was using your script (awesome work btw!) and ran into a Python UnicodeEncodeError. I fixed the issue by updating lines 106, 159, 184, 200, and 216 to update the ‘with open’ portions to include “encoding=‘utf-8’”.

**Comment by iandday** [comment] 2023-04-23 21:24
interesting, did you convert the files downloaded from the compliance center before using the parser?  Latin-1 still works for me with content from the compliance center

**Comment by Hilljack4n6** [comment] 2023-04-24 01:06
> interesting, did you convert the files downloaded from the compliance center before using the parser? Latin-1 still works for me with content from the compliance center

I exported from the compliance center and used the raw CSV for the script. I later discovered the text the script had issues with. There were some Teams chat names that titles utilizing some strange fonts and strange characters.

**Comment by angry-bender** [comment] 2023-07-17 12:18
I can confirm the same issue when exporting and converting using Search-UnifiedAuditLog from Powershell, making the changes @Hilljack4n6 Seemed to fix it right up, thank you :-)

**Comment by angry-bender** [comment] 2023-07-17 12:19
Its probably based on user input tbh, it was erroring on exchange operations, where operations like Set-MailboxRule have user input within those strings. I've seen the UAL use both UTF-8 or sometimes UTF-16LE

**Comment by Hilljack4n6** [comment] 2023-07-17 12:29
> Its probably based on user input tbh, it was erroring on exchange operations, where operations like Set-MailboxRule have user input within those strings. I've seen the UAL use both UTF-8 or sometimes UTF-16LE

You are correct. Mine did this originally because of a group chat a user was in. The name of the group chat had some special characters, such as emojis.

**Comment by angry-bender** [comment] 2023-07-17 14:07
I wonder if its work using the chardetect library for this project, could help to detect the encoding of the file where there might be a curveball and flagging it, https://github.com/chardet/chardet

**Comment by angry-bender** [comment] 2023-07-17 14:08
> > Its probably based on user input tbh, it was erroring on exchange operations, where operations like Set-MailboxRule have user input within those strings. I've seen the UAL use both UTF-8 or sometimes UTF-16LE
> 
> You are correct. Mine did this originally because of a group chat a user was in. The name of the group chat had some special characters, such as emojis.

Checks out, I wonder if its work using the chardetect library for this project, could help to detect the encoding of the file where there might be a curveball and flagging it, https://github.com/chardet/chardet

**Comment by iandday** [comment] 2023-07-17 21:32
merged, thanks for the contribution!

**Closed as completed by iandday** 2023-07-17 21:32 UTC
